version: '3.4'

services:
  MyDb:
    image: postgres:11-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=er42k2l5
      - POSTGRES_DB=postgres

  webapp:
    image: ${DOCKER_REGISTRY-}webapp
    build:
      context: .
      dockerfile: WebApp\Dockerfile
    ports:
      - "7130:7130"
    depends_on:
      - "MyDb"

  proxy:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro \
    ports:
      - "81:80"